name: Build and Release - DRAFT

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select Branch'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - development
        # add other branches here if necessary

permissions:
  contents: write  # Required for creating releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    container:
      image: debian:bookworm
      options: --privileged

    steps:
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install -y git curl wget pkg-config cmake make binutils build-essential gzip bzip2 tar unzip
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" > /etc/apt/sources.list.d/github-cli.list
          apt-get update
          apt-get install -y gh

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}
          fetch-depth: 0  # fetch full history including tags

      - name: Trust workspace directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Get current tag
        shell: bash
        id: vars
        run: |
          tag=$(git describe --tags --abbrev=0)
          echo "release=$tag" >> "$GITHUB_OUTPUT"
          if [[ "${{ github.event_name }}" = "workflow_dispatch" && "${{ github.event.inputs.branch }}" == "development" ]]; then
            echo "tag=${{ github.event.inputs.branch }}-$(date +%Y%m%d-%H%M%S)" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"
          fi
          # Get latest toolchain tag
          toolchain_tag=$(gh release view --repo rabit-wisp/toolchain --json tagName -q .tagName)
          echo "toolchain_release=$toolchain_tag" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Download latest release assets
        run: |
          gh release download "${{ steps.vars.outputs.toolchain_release }}" --repo rabit-wisp/toolchain --dir ./downloaded-assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Unpack toolchains
        run: |
          for i in ./downloaded-assets/*.tar.gz
          do
            tar zxvf $i
          done

      - name: Make and build each target toolchain
        run: |
          mkdir artifacts
          for i in cmake/toolchains/*.cmake
          do
            mkdir build/$(basename $i)
            cd build/$(basename $i)
            cmake -DCMAKE_TOOLCHAIN_FILE=$i ..
            make
            cp binaries/* ../artifacts/
            cd ..
          done

      - name: Make ipk packages
        run: |
          cd scripts
          ./build-base.sh
          ./build-luci.sh
          mv ../ipk-output/*.ipk artifacts


      - name: Compress artifacts
        run: |
          for i in artifacts/*
          do
            [[ "$i" == *.ipk ]] && continue
            gzip $i
          done

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.release }}
          files: artifacts/*.gz
          draft: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
